stages:
  - test

default:
  image: centos:8

.dind:
  tags:
    - dind
  services:
    - name: docker:dind
      alias: localhost
      command: ["--mtu=1300"]
  image: docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_BUILDKIT: 1

tests:
  extends: .dind
  stage: test
  script:
    - docker run -p5432:5432 --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres
    - docker build -f Dockerfile.test -t luapg .
    - docker run --network=host --env PGHOST='127.0.0.1' --env PGUSER='postgres' --env PGPASSWORD='mysecretpassword' -it --rm luapg
