FROM centos:7

RUN yum -y install postgresql-devel \
    yum -y install sudo \
    yum -y install git

RUN curl -L https://tarantool.io/installer.sh | VER=2.5 sudo -E bash

RUN yum -y install tarantool-devel

ENV PATH=$PWD:$PATH

ADD . /opt/luapg

WORKDIR /opt/luapg

RUN yum -y install cmake

RUN tarantoolctl rocks install luatest 0.5.2

ENTRYPOINT .rocks/bin/luatest -c
