FROM centos:7

ARG TARANTOOL_REPO

ARG PGDATABASE
ARG PGUSER
ARG PGPASSWORD

RUN yum -y install postgresql-devel \
    yum -y install sudo

RUN curl -L https://tarantool.io/installer.sh | VER=2.5 sudo -E bash

ENV PATH=$PWD:$PATH

ADD . /opt/luapg

WORKDIR /opt/luapg

RUN tarantoolctl rocks install luatest 0.5.2

RUN .rocks/bin/luatest -c
